// Backend integration point: Replace with real API data from your backend
import {
  AgentConversationItem,
  QuickActionItem,
  AutomationItem,
  AgentAlertItem,
  AgentTaskHistoryItem,
  WorkflowTemplateItem,
  AgentOverview,
} from './types';

export const mockAgentOverview: AgentOverview = {
  todayTasks: 12,
  runningAutomations: 4,
  pendingAlerts: 5,
  aiAssisted: 27,
  overdueTenantsCount: 3,
  expiringContractsCount: 4,
};

export const mockConversations: AgentConversationItem[] = [
  {
    id: 'msg-1',
    role: 'assistant',
    content: 'Xin chào! Tôi là AI Agent của MotelManage. Tôi có thể giúp bạn quản lý phòng trọ, theo dõi hợp đồng, tổng hợp chi phí và tự động hóa các công việc hàng ngày. Hôm nay bạn cần hỗ trợ gì?',
    createdAt: '2024-07-15T08:00:00Z',
    messageType: 'text',
    relatedModule: 'general',
  },
  {
    id: 'msg-2',
    role: 'user',
    content: 'Liệt kê khách thuê còn nợ tiền',
    createdAt: '2024-07-15T08:02:00Z',
    messageType: 'text',
    relatedModule: 'tenants',
  },
  {
    id: 'msg-3',
    role: 'assistant',
    content: 'Tôi đã kiểm tra dữ liệu công nợ. Hiện có **3 khách thuê** chưa thanh toán tiền phòng với tổng số tiền còn nợ là **7.800.000 đ**:',
    createdAt: '2024-07-15T08:02:05Z',
    messageType: 'list',
    relatedModule: 'tenants',
    listItems: [
      '🏠 Phòng A101 — Nguyễn Thị Lan — Nợ 2.600.000 đ (quá hạn 15 ngày)',
      '🏠 Phòng B203 — Trần Văn Minh — Nợ 2.800.000 đ (quá hạn 8 ngày)',
      '🏠 Phòng C305 — Lê Thị Hoa — Nợ 2.400.000 đ (quá hạn 3 ngày)',
    ],
    suggestedActions: [
      { label: 'Gửi nhắc nhở tất cả', actionType: 'send_reminder' },
      { label: 'Xem danh sách khách thuê', actionType: 'navigate', href: '/tenant-management' },
      { label: 'Tạo tác vụ follow-up', actionType: 'create_task' },
    ],
  },
  {
    id: 'msg-4',
    role: 'user',
    content: 'Hợp đồng nào sắp hết hạn trong 30 ngày tới?',
    createdAt: '2024-07-15T08:05:00Z',
    messageType: 'text',
    relatedModule: 'contracts',
  },
  {
    id: 'msg-5',
    role: 'assistant',
    content: 'Tôi đã quét toàn bộ hợp đồng đang hiệu lực. Có **4 hợp đồng** sẽ hết hạn trong 30 ngày tới:',
    createdAt: '2024-07-15T08:05:08Z',
    messageType: 'list',
    relatedModule: 'contracts',
    listItems: [
      '📋 HĐ-2024-018 — Phòng A102 — Nguyễn Văn An — Hết hạn 20/07/2024 (còn 5 ngày)',
      '📋 HĐ-2024-022 — Phòng B201 — Phạm Thị Bích — Hết hạn 25/07/2024 (còn 10 ngày)',
      '📋 HĐ-2024-031 — Phòng C301 — Hoàng Văn Đức — Hết hạn 01/08/2024 (còn 17 ngày)',
      '📋 HĐ-2024-035 — Phòng A205 — Vũ Thị Mai — Hết hạn 10/08/2024 (còn 26 ngày)',
    ],
    suggestedActions: [
      { label: 'Xem tất cả hợp đồng', actionType: 'navigate', href: '/contract-management' },
      { label: 'Tạo nhắc gia hạn', actionType: 'create_task' },
    ],
  },
];

export const mockQuickActions: QuickActionItem[] = [
  {
    id: 'qa-1',
    title: 'Gửi nhắc nợ tiền phòng',
    description: 'Tự động gửi thông báo nhắc thanh toán đến các khách thuê còn nợ',
    icon: '💰',
    actionType: 'chat_prompt',
    relatedModule: 'tenants',
    prompt: 'Liệt kê khách thuê còn nợ tiền và gợi ý nội dung nhắc nhở',
  },
  {
    id: 'qa-2',
    title: 'Kiểm tra hợp đồng sắp hết hạn',
    description: 'Quét và tổng hợp các hợp đồng sẽ hết hạn trong 30 ngày tới',
    icon: '📋',
    actionType: 'chat_prompt',
    relatedModule: 'contracts',
    prompt: 'Hợp đồng nào sắp hết hạn trong 30 ngày tới?',
  },
  {
    id: 'qa-3',
    title: 'Tạo bài đăng cho phòng trống',
    description: 'AI gợi ý nội dung bài đăng hấp dẫn cho các phòng đang trống',
    icon: '📢',
    actionType: 'chat_prompt',
    relatedModule: 'posts',
    prompt: 'Gợi ý bài đăng để lấp đầy phòng trống',
  },
  {
    id: 'qa-4',
    title: 'Tóm tắt chi phí tuần này',
    description: 'Tổng hợp và phân tích các khoản chi phí trong tuần hiện tại',
    icon: '📊',
    actionType: 'chat_prompt',
    relatedModule: 'expenses',
    prompt: 'Tóm tắt chi phí tháng này',
  },
  {
    id: 'qa-5',
    title: 'Nhắc lịch bảo trì',
    description: 'Kiểm tra và tạo lịch bảo trì định kỳ cho các phòng và thiết bị',
    icon: '🔧',
    actionType: 'chat_prompt',
    relatedModule: 'rooms',
    prompt: 'Tạo nhắc việc kiểm tra bảo trì phòng trống',
  },
  {
    id: 'qa-6',
    title: 'Báo cáo vận hành tuần này',
    description: 'Tổng hợp nhanh tình hình vận hành nhà trọ trong tuần',
    icon: '📈',
    actionType: 'chat_prompt',
    relatedModule: 'reports',
    prompt: 'Cho tôi báo cáo nhanh tình hình vận hành tuần này',
  },
];

export const mockAutomations: AutomationItem[] = [
  {
    id: 'auto-1',
    name: 'Nhắc khách thanh toán tiền phòng hàng tháng',
    description: 'Tự động gửi thông báo nhắc thanh toán vào ngày 25 hàng tháng cho tất cả khách thuê',
    triggerType: 'schedule',
    frequency: 'monthly',
    status: 'active',
    lastRunAt: '2024-06-25T08:00:00Z',
    nextRunAt: '2024-07-25T08:00:00Z',
    module: 'tenants',
    isEnabled: true,
    runCount: 6,
  },
  {
    id: 'auto-2',
    name: 'Cảnh báo hợp đồng sắp hết hạn',
    description: 'Quét và gửi cảnh báo khi có hợp đồng sẽ hết hạn trong vòng 30 ngày',
    triggerType: 'schedule',
    frequency: 'weekly',
    status: 'active',
    lastRunAt: '2024-07-08T07:00:00Z',
    nextRunAt: '2024-07-15T07:00:00Z',
    module: 'contracts',
    isEnabled: true,
    runCount: 12,
  },
  {
    id: 'auto-3',
    name: 'Tổng hợp chi phí hàng tuần',
    description: 'Tự động tổng hợp và gửi báo cáo chi phí vào mỗi thứ Hai',
    triggerType: 'schedule',
    frequency: 'weekly',
    status: 'active',
    lastRunAt: '2024-07-08T06:00:00Z',
    nextRunAt: '2024-07-15T06:00:00Z',
    module: 'expenses',
    isEnabled: true,
    runCount: 8,
  },
  {
    id: 'auto-4',
    name: 'Nhắc lịch kiểm tra phòng trống',
    description: 'Tạo nhắc việc kiểm tra tình trạng phòng trống mỗi tuần',
    triggerType: 'schedule',
    frequency: 'weekly',
    status: 'paused',
    lastRunAt: '2024-07-01T09:00:00Z',
    nextRunAt: null,
    module: 'rooms',
    isEnabled: false,
    runCount: 4,
  },
  {
    id: 'auto-5',
    name: 'Tạo báo cáo vận hành đầu tháng',
    description: 'Tự động tạo báo cáo tổng hợp vận hành vào ngày 1 hàng tháng',
    triggerType: 'schedule',
    frequency: 'monthly',
    status: 'active',
    lastRunAt: '2024-07-01T05:00:00Z',
    nextRunAt: '2024-08-01T05:00:00Z',
    module: 'reports',
    isEnabled: true,
    runCount: 3,
  },
  {
    id: 'auto-6',
    name: 'Gợi ý nội dung đăng bài khi có phòng trống',
    description: 'Khi phát hiện phòng trống quá 7 ngày, AI tự động gợi ý nội dung bài đăng',
    triggerType: 'condition',
    frequency: 'daily',
    status: 'error',
    lastRunAt: '2024-07-10T10:00:00Z',
    nextRunAt: '2024-07-15T10:00:00Z',
    module: 'posts',
    isEnabled: false,
    runCount: 2,
  },
];

export const mockAlerts: AgentAlertItem[] = [
  {
    id: 'alert-1',
    severity: 'high',
    title: '3 khách thuê đã quá hạn thanh toán',
    description: 'Nguyễn Thị Lan (A101), Trần Văn Minh (B203), Lê Thị Hoa (C305) chưa thanh toán tiền phòng. Tổng nợ: 7.800.000 đ',
    actionLabel: 'Xem khách thuê',
    relatedRoute: '/tenant-management',
    createdAt: '2024-07-15T07:00:00Z',
  },
  {
    id: 'alert-2',
    severity: 'high',
    title: '4 hợp đồng sẽ hết hạn trong 14 ngày',
    description: 'Có 4 hợp đồng sắp hết hạn cần liên hệ gia hạn hoặc chuẩn bị thủ tục kết thúc hợp đồng',
    actionLabel: 'Xem hợp đồng',
    relatedRoute: '/contract-management',
    createdAt: '2024-07-15T07:05:00Z',
  },
  {
    id: 'alert-3',
    severity: 'medium',
    title: 'Chi phí sửa chữa tuần này tăng 28%',
    description: 'Chi phí sửa chữa tuần này đạt 3.200.000 đ, tăng 28% so với tuần trước. Cần kiểm tra lại các khoản chi',
    actionLabel: 'Đi đến báo cáo',
    relatedRoute: '/reports',
    createdAt: '2024-07-15T07:10:00Z',
  },
  {
    id: 'alert-4',
    severity: 'medium',
    title: '2 phòng trống hơn 20 ngày chưa có bài đăng mới',
    description: 'Phòng A103 và B204 đã trống 22 ngày nhưng chưa có bài đăng tìm khách mới. Cần đăng bài ngay để tránh thất thu',
    actionLabel: 'Tạo bài đăng',
    relatedRoute: '/post-management',
    createdAt: '2024-07-14T15:00:00Z',
  },
  {
    id: 'alert-5',
    severity: 'info',
    title: 'Tỷ lệ lấp đầy khu B giảm so với tháng trước',
    description: 'Khu B hiện đạt 75% lấp đầy, giảm 10% so với tháng 6. Cần xem xét chiến lược marketing cho khu này',
    actionLabel: 'Nhờ AI xử lý',
    relatedRoute: '/reports',
    createdAt: '2024-07-14T12:00:00Z',
  },
];

export const mockTaskHistory: AgentTaskHistoryItem[] = [
  {
    id: 'task-1',
    name: 'AI tổng hợp công nợ tuần này',
    taskType: 'ai_summary',
    triggerSource: 'manual',
    status: 'completed',
    createdAt: '2024-07-15T08:05:00Z',
    resultSummary: 'Tổng công nợ: 7.800.000 đ — 3 khách thuê',
    module: 'tenants',
  },
  {
    id: 'task-2',
    name: 'Automation — Nhắc thanh toán tháng 7',
    taskType: 'automation',
    triggerSource: 'automation',
    status: 'completed',
    createdAt: '2024-07-14T08:00:00Z',
    resultSummary: 'Đã gửi 18 thông báo nhắc nhở thành công',
    module: 'tenants',
  },
  {
    id: 'task-3',
    name: 'AI tạo bài đăng phòng A103',
    taskType: 'ai_generated',
    triggerSource: 'manual',
    status: 'completed',
    createdAt: '2024-07-13T14:30:00Z',
    resultSummary: 'Đã tạo 2 mẫu bài đăng cho phòng A103',
    module: 'posts',
  },
  {
    id: 'task-4',
    name: 'Quét hợp đồng sắp hết hạn',
    taskType: 'scan',
    triggerSource: 'schedule',
    status: 'completed',
    createdAt: '2024-07-13T07:00:00Z',
    resultSummary: 'Phát hiện 4 hợp đồng hết hạn trong 30 ngày',
    module: 'contracts',
  },
  {
    id: 'task-5',
    name: 'Tổng hợp chi phí tuần 28',
    taskType: 'digest',
    triggerSource: 'automation',
    status: 'completed',
    createdAt: '2024-07-08T06:00:00Z',
    resultSummary: 'Tổng chi phí: 4.850.000 đ — 7 khoản',
    module: 'expenses',
  },
  {
    id: 'task-6',
    name: 'Automation — Gợi ý bài đăng phòng trống',
    taskType: 'automation',
    triggerSource: 'automation',
    status: 'failed',
    createdAt: '2024-07-10T10:00:00Z',
    resultSummary: 'Lỗi kết nối module bài đăng',
    module: 'posts',
  },
  {
    id: 'task-7',
    name: 'Báo cáo vận hành tháng 7',
    taskType: 'ai_summary',
    triggerSource: 'schedule',
    status: 'completed',
    createdAt: '2024-07-01T05:00:00Z',
    resultSummary: 'Báo cáo đã được tạo và gửi đến admin',
    module: 'reports',
  },
  {
    id: 'task-8',
    name: 'AI phân tích tỷ lệ lấp đầy',
    taskType: 'ai_summary',
    triggerSource: 'manual',
    status: 'completed',
    createdAt: '2024-07-12T11:00:00Z',
    resultSummary: 'Tỷ lệ lấp đầy tổng thể: 90% — Khu B cần chú ý',
    module: 'rooms',
  },
];

export const mockWorkflowTemplates: WorkflowTemplateItem[] = [
  {
    id: 'wf-1',
    name: 'Thu tiền phòng đầu tháng',
    description: 'Tự động nhắc khách thuê thanh toán, theo dõi trạng thái và tổng hợp công nợ vào đầu mỗi tháng',
    trigger: 'Ngày 1 hàng tháng lúc 8:00',
    outcome: 'Gửi thông báo nhắc nhở, tạo danh sách công nợ, cảnh báo quá hạn',
    module: 'tenants',
    estimatedTime: '~5 phút',
  },
  {
    id: 'wf-2',
    name: 'Theo dõi hợp đồng sắp hết hạn',
    description: 'Quét hàng tuần và cảnh báo các hợp đồng sẽ hết hạn trong 30 ngày, gợi ý liên hệ gia hạn',
    trigger: 'Mỗi thứ Hai lúc 7:00',
    outcome: 'Danh sách hợp đồng cần xử lý, nhắc việc liên hệ khách thuê',
    module: 'contracts',
    estimatedTime: '~3 phút',
  },
  {
    id: 'wf-3',
    name: 'Xử lý phòng trống lâu ngày',
    description: 'Phát hiện phòng trống quá 7 ngày, tự động gợi ý nội dung bài đăng và nhắc chủ nhà đăng tin',
    trigger: 'Hàng ngày lúc 9:00',
    outcome: 'Gợi ý bài đăng, nhắc đăng lại, theo dõi hiệu quả',
    module: 'posts',
    estimatedTime: '~2 phút',
  },
  {
    id: 'wf-4',
    name: 'Tổng hợp chi phí cuối tuần',
    description: 'Tự động tổng hợp tất cả chi phí trong tuần, phân loại và gửi báo cáo tóm tắt',
    trigger: 'Mỗi Chủ nhật lúc 20:00',
    outcome: 'Báo cáo chi phí tuần, phân tích biến động, gợi ý tiết kiệm',
    module: 'expenses',
    estimatedTime: '~4 phút',
  },
  {
    id: 'wf-5',
    name: 'Nhắc bảo trì định kỳ',
    description: 'Tạo lịch bảo trì định kỳ cho phòng và thiết bị, nhắc nhở trước 3 ngày',
    trigger: 'Theo lịch bảo trì đã cài đặt',
    outcome: 'Danh sách việc cần bảo trì, nhắc việc cho quản lý',
    module: 'rooms',
    estimatedTime: '~2 phút',
  },
  {
    id: 'wf-6',
    name: 'Theo dõi khách thuê chậm thanh toán',
    description: 'Theo dõi lịch sử thanh toán, phát hiện khách thuê có xu hướng chậm trả và gợi ý biện pháp',
    trigger: 'Hàng tuần vào thứ Tư',
    outcome: 'Danh sách khách thuê cần theo dõi, lịch sử thanh toán, gợi ý xử lý',
    module: 'tenants',
    estimatedTime: '~5 phút',
  },
];
